### ISSUE TITLE
Error: -bash: curl: command not found

### ISSUE THREAD

**Issue by 42thcoder** [cmlh/Maltego-Entities-Mirror#1]
Hello I try to ran you're script and I find to execute it I get this error:

-bash: curl: command not found
-bash: curl: command not found
-bash: curl: command not found

and then is error all to screen. Please repare.

**Comment by cmlh** [comment]
I'll assume you are referring to the "update_entities_mirror.sh" of https://github.com/cmlh/Maltego-Entities-Mirror/commit/3421127999bba6cf44001be42be1959eb200ffb7 as the "script" in the issue description?

cURL can be downloaded from http://curl.haxx.se/ or made available as a port and/or package from the web page of your Operating System.  For instance, cURL is available on OSX i.e. https://developer.apple.com/library/mac/#documentation/Darwin/Reference/ManPages/man1/curl.1.html

That stated, I didn't intend for the "script" to be executed by an end user since it will modify the .git repository.  Rather the Maltego Entities that this "script" retrieves can be downloaded from https://github.com/cmlh/Maltego-Entities-Mirror/tree/master/mirror/www which I could make available as a separate download independent of .git?

Please let me know if I have misunderstood your issue or there is an alternative to resolve this issue that I have not considered?

**Comment by cmlh** [comment]
@42thcoder,

I wrote https://github.com/cmlh/Maltego-Entities-Mirror/blob/create_tarball/create_tarball.sh which creates https://github.com/cmlh/Maltego-Entities-Mirror/tree/create_tarball/Releases so the Maltego Entities can be downloaded rather than cloning this .git repository.

Can you please let me know if this meets your expectation?
